# Generated by Django 2.2.5 on 2019-12-14 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_room_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Profile'),
            preserve_default=False,
        ),
    ]
